### ISSUE TITLE
Selecting VirtualSMC and VodooI2C plugins

### ISSUE THREAD

**Issue by JJTech0130** [LEXUGE/oceanix#2]
Is there a way to select which plugins of VirtualSMC and VodooI2C are installed? I don't want to use them all.

**Comment by LEXUGE** [comment]
Yes, only plugins enabled will take affect.
See https://github.com/LEXUGE/opencore-cfg/blob/main/modules/x1c7/Kernel.nix

**Comment by JJTech0130** [comment]
Yes, I understand that, I just meant they're all copied into the EFI, using up unnecessary space.

**Comment by LEXUGE** [comment]
I deliberately did this to avoid unnecessary complexity in code. Practically, the disk usage is not a concern here. However, it could be optimized.

**Comment by JJTech0130** [comment]
I guess that makes sense. It just offends my sensibilities to copy unnecessary files, just to disable them 🤣
